name: college_app
description: "A modern college mini app for students"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  
  # Image loading and caching
  cached_network_image: ^3.3.1
  
  # State Management
  provider: ^6.1.1
  
  # Firebase (keeping your existing setup)
  firebase_core: ^2.30.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.17.4
  
  # Date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
